name: GitHub Actions
on: [push]
jobs:
  golang-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
      - run: go mod init
      - run: make test
