name: GitHub Actions
on: [push]
jobs:
  golang-tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: cedrickring/golang-action@1.6.0
      - run: make test
    
