name: Go
on: [push, pull_request]
jobs:
  golang-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.3
    - name: initializing go mod
      run: go mod init golangtasks
    - name: run tests
      run: make test
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.3
    - name: initializing go mod
      run: go mod init golangtasks
    - name: installing
      run: sudo make install
    - name: running linter
      run: make linter
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: SonarCloud Scan
     - uses: sonarsource/sonarcloud-github-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
